### ISSUE TITLE
Proposal: Ignore session for some request even SessionOn = true

### ISSUE THREAD

**Issue by flycash** [beego/beego#4176] opened 2020-08-19 14:57 UTC
#2787 #4169 

For now, we only have one global configuration SessionOn to control whether using session.

If SessionOn = true, all request except static resources carry session information. 

But sometimes, we want to close the session for some path.

For example, we have two routes, one is `/session/xxxx`, which means that we need session;
another is `/no-session/xxxx`.

But I don't have any good design. One simple way is that change `Router` method, add more option to control the behavior:
```go
func Router(rootpath string, c ControllerInterface, mappingMethods ...string) *App {
	BeeApp.Handlers.Add(rootpath, c, mappingMethods...)
	return BeeApp
}
```

```go
func Router(rootpath string, c ControllerInterface, opts Opts) *App {
	BeeApp.Handlers.Add(rootpath, c, mappingMethods...)
	return BeeApp
}
```

**Comment by luudis** [comment] 2020-09-21 02:13
I have the same demand and is there any further progress about this proposal?

**Comment by flycash** [comment] 2020-09-22 05:28
No, would you like to support this feature?

**Comment by AllenX2018** [comment] 2020-11-04 03:55
Hello

I came up with two options. 

### Modify interface
The first one is like you provided, change the original function
```go
func Router(rootpath string, c ControllerInterface, mappingMethods ...string) *HttpServer
```
to
```go
func Router(rootpath string, c ControllerInterface, opts Opts, mappingMethods ...string) *HttpServer
```
then use `opts` to transfer the bool value of the session switch.
However, this will change the `Router` interface. Will the users who switch from the earlier version need to modify the interface in a large scope?

### Add new interface
The second method is to add a new interface for configuring the session switch. For example,
```go
func Session(rootpath string, opts Opts, mappingMethod ...string) error
```
Calling this interface can search for the corresponding route in the prefix tree `routers` in `ControllerRegister` and set `sessionOn` in `ControllerInfo`。Correspondingly, the `sessionOn bool` field is added to the `ControllerInfo` structure.

Adding this interface means that route binding and route session setting are performed in two steps. However, this doesn't affect the original interface `Router`. In addition, if the user is migrated to the new version but doesn't call the session setting interface, the session is configured globally and doesn't affect the running of the original user code.

**Comment by flycash** [comment] 2020-11-05 14:24
> Hello
> 
> I came up with two options.
> 
> ### Modify interface
> The first one is like you provided, change the original function
> 
> ```go
> func Router(rootpath string, c ControllerInterface, mappingMethods ...string) *HttpServer
> ```
> 
> to
> 
> ```go
> func Router(rootpath string, c ControllerInterface, opts Opts, mappingMethods ...string) *HttpServer
> ```

I like this solution. How about:
```go
func RouterWithOpt(rootpath string, c ControllerInterface, opt... Opts) *HttpServer
```
And the `mappingMethods` will be an option.

**Comment by AllenX2018** [comment] 2020-11-06 01:26
> > Hello
> > I came up with two options.
> > ### Modify interface
> > The first one is like you provided, change the original function
> > ```go
> > func Router(rootpath string, c ControllerInterface, mappingMethods ...string) *HttpServer
> > ```
> > 
> > 
> > to
> > ```go
> > func Router(rootpath string, c ControllerInterface, opts Opts, mappingMethods ...string) *HttpServer
> > ```
> 
> I like this solution. How about:
> 
> ```go
> func RouterWithOpt(rootpath string, c ControllerInterface, opt... Opts) *HttpServer
> ```
> 
> And the `mappingMethods` will be an option.

This solution is good! 
Could the ```opt``` be an interface? And the function could be:
```go
func RouterWithOpt(rootpath string, c ControllerInterface, opt ...interface{}) *HttpServer
```
We can call it like:
```go
RouterWithOpt("/", &Controller{}, "get:method")
```
or 
```go
RouterWithOpt("/", &Controller{}, "get:method", false)
```

**Comment by flycash** [comment] 2020-11-08 11:57
> Could the `opt` be an interface?
I think using `interface` is not a good idea.
Assume that we have several parameters, and I only want to pass 3rd parameter, I am forced to pass 1st and 2nd parameters.

Another concern is that users easily pass wrong parameters since missing type checking. 

And I think is not readable.

**Comment by AllenX2018** [comment] 2020-11-08 14:18
> > Could the `opt` be an interface?
> 
> I think using `interface` is not a good idea.
> Assume that we have several parameters, and I only want to pass 3rd parameter, I am forced to pass 1st and 2nd parameters.
> 
> Another concern is that users easily pass wrong parameters since missing type checking.
> 
> And I think is not readable.

How about define  `Opts` like
```go
type struct Opts {
        Key string
        Value string
}
````
and use like `Opts{Key: "SessionOn", Value: "true"}` or `Opts{Key: "mappingmethods", Value: "get: func1"}` ?

**Comment by flycash** [comment] 2020-11-09 13:19
I prefer [options pattern](https://www.sohamkamani.com/golang/options-pattern/)

**Comment by AllenX2018** [comment] 2020-11-12 06:49
It's a good idea. And how do we handle previos global config `cfg.WebConfig.Session.SessionOn`?
 A simple way is that we don't use it any more, and set the default value of every router's `SessionOn` is false, unless we modify it in `opts`.

**Comment by AllenX2018** [comment] 2020-11-12 07:08
And how about other route function, such as `AutoRouter`, `Get`, `Handler`, `NSRouter` and so on ? I think all of them should be modied like `Router` if we want to set `SessionOn` for any kind of router.

**Comment by AllenX2018** [comment] 2020-11-12 07:39
I am glad to solve this issue once the solution is confirmed. You can assign it to me~ @flycash

**Comment by flycash** [comment] 2020-11-12 13:14
> how do we handle previos global config cfg.WebConfig.Session.SessionOn?
I think we could keep this config item. If it's true, it means that all routes will use session which keeps compatible with current behavior.  
Here we have two cases:
```
SessionOn=true
Route(xxx, WithOutSessionOpt) // don't use session
```
and 
```
SessionOn = false
Route(xxx,WithSession) // use session
```

That means `SessionOn` is a global config item and we also allow users use route-specific config item.

> such as AutoRouter, Get, Handler, NSRouter and so on ?

I belive that we could ignore those methods at phase1. And we release this feature and collect the feedback and then decide whether need to enhance those methods. But if you want to enhance them in the same PR, just do it.

**Comment by AllenX2018** [comment] 2020-11-21 09:23
If we want to implement this logic
> ```go
> SessionOn = false
> Route(xxx,WithSession) // use session
> ```

If the global `SessionOn` is `false`,  the function `registerSession` will do nothing and `Manager.config` won't be initialized. 
As a result, if we use session and get session id, the line following will panic because of nil pointer.
https://github.com/astaxie/beego/blob/05d8e293f7f314f6741213a9d943ce0be770723c/server/web/session/session.go#L180

I don't have any good design. A simple solution is that we remove the judgment condition of global `sessionOn` and always initialize `Manager.config` in function `registerSession`.

**Comment by flycash** [comment] 2020-11-23 13:00
@AllenX2018 We could only support 
```
SessionOn=true
Route(xxx, WithOutSessionOpt) // don't use session
```

**Closed** 2021-01-24 11:12 UTC
Labels: V2.0, area/context, area/session, help-wanted

**Comment by HaoKunT** [comment] 2023-04-23 13:15
Hello, I use v1.x and also meet this requirement. Can this feature be apply on v1.x ?
